apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    env: demo
spec:
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
      name: nginx-ds
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80

